name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  check:
    name: cargo check

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo check

  fmt-check:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --version
      - run: cargo fmt --all -- --check --color=always

  test-rust:
    name: cargo test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
      - run: cargo test

  package:
    uses: ./.github/workflows/package.yml

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --component clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --version
      - run: cargo clippy --all-targets --all-features -- -D warnings

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'

  fish-check:
    name: check fish code

    strategy:
      matrix:
        include:
          - ppa: ppa:fish-shell/release-3
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ${{ matrix.ppa }}
          sudo apt-get update -y
          sudo apt-get install fish
      - name: Fish syntax check
        run: find . -iname '*.fish' -print0 | xargs -n1 -0t fish -n

  python-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install flake8
      - run: flake8 .

  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install black
      - run: black --check .
